/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    input [1:0] toggleD,
    output reg [1:0] ledD,
    input [15:0] user_input,
    output reg [15:0] user_input_led,
    input toggleAB,
    input enter_btn,
    output reg [3:0] stage,
    output reg right_led,
    output reg wrong_led,
    output reg buzz,
    output reg [9:0] timer_led
  );
  
  
  
  reg rst;
  
  integer on;
  
  integer off;
  
  integer true;
  
  integer false;
  
  wire [2-1:0] M_eternite_ledD;
  wire [16-1:0] M_eternite_user_input_led;
  wire [4-1:0] M_eternite_stage;
  wire [1-1:0] M_eternite_right_led;
  wire [1-1:0] M_eternite_wrong_led;
  wire [1-1:0] M_eternite_buzz;
  wire [10-1:0] M_eternite_timer_led;
  reg [1-1:0] M_eternite_clk;
  reg [1-1:0] M_eternite_rst;
  reg [2-1:0] M_eternite_toggleD;
  reg [16-1:0] M_eternite_user_input;
  reg [1-1:0] M_eternite_toggleAB;
  reg [1-1:0] M_eternite_enter_btn;
  eternite_fsm_1 eternite (
    .clk(M_eternite_clk),
    .rst(M_eternite_rst),
    .toggleD(M_eternite_toggleD),
    .user_input(M_eternite_user_input),
    .toggleAB(M_eternite_toggleAB),
    .enter_btn(M_eternite_enter_btn),
    .ledD(M_eternite_ledD),
    .user_input_led(M_eternite_user_input_led),
    .stage(M_eternite_stage),
    .right_led(M_eternite_right_led),
    .wrong_led(M_eternite_wrong_led),
    .buzz(M_eternite_buzz),
    .timer_led(M_eternite_timer_led)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_2 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'hff;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    M_eternite_user_input = user_input;
    user_input_led = user_input;
    buzz = M_eternite_buzz;
    M_eternite_clk = clk;
    M_eternite_rst = rst;
    M_eternite_toggleAB = toggleAB;
    M_eternite_enter_btn = enter_btn;
    stage = M_eternite_stage;
    M_eternite_toggleD = toggleD;
    ledD = M_eternite_ledD;
    timer_led = M_eternite_timer_led;
    right_led = M_eternite_right_led;
    wrong_led = M_eternite_wrong_led;
  end
endmodule
