/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module eternite_alufunctions_1 (
    input [15:0] a,
    input [15:0] b,
    input [2:0] alufn,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out = 1'h0;
    
    case (alufn)
      3'h1: begin
        out = a + b;
      end
      3'h6: begin
        out = a * b;
      end
      3'h2: begin
        out = ~(a | b);
      end
      3'h3: begin
        out = a ^ b;
      end
      3'h5: begin
        out = a;
      end
      3'h4: begin
        out = a == b;
      end
      3'h7: begin
        out = (~(a[15+0-:1] + b[15+0-:1]) & a[15+0-:1] & b[15+0-:1]) || (~a[15+0-:1] & ~b[15+0-:1] & (a[15+0-:1] + b[15+0-:1]));
      end
    endcase
  end
endmodule
